out_dir: results
metric_best: accuracy
wandb:
  use: False
dataset:
  format: OGB
  name: ogbg-ppa
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: PPANode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: PPAEdge
  edge_encoder_bn: False
train:
  mode: custom
  batch_size: 64
  eval_period: 1
  ckpt_period: 100
model:
  type: GatedDeltaNetModel
  loss_fun: cross_entropy
  graph_pooling: mean
gt:
  layer_type: GatedDeltaNet
  layers: 3
  n_heads: 8
  dim_hidden: 256
  dropout: 0.1
  layer_norm: False
  batch_norm: True
  perm_ensemble: 1
  perm_lambda: 0.0
  perm_mode: none
  perm_pct: 0
  dual_fla: False
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 2
  dim_inner: 256
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0003
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
